language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng build --prod
deploy:
  provider: s3
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  bucket: savings.reedmartz.com
  skip_cleanup: true
  local_dir: dist/saving-goals
  cache_control: "max-age=86400"
  on:
    branch: develop
notifications:
  email:
    on_failure: change
    on_success: always
